---

experiment: distill
model: resnet50
data_dir: /tmp/imagenet 

epochs: 100
batch_size: 64

sched: step
decay_epochs: 300
warmup_epochs: 5

# smoothing to zero
smoothing: 0

# Data and Model
hflip: 0.5
vflip: 0.0
crop_pct: 1.0

# Optimizer
lr: 1.0
opt: iam
opt_kwargs: {'lmbda': 9.0}
weight_decay: 0.000005
run_id: 0

# Other
workers: 16
log_wandb: true
wandb_project_name: iam-distill
