---

experiment: distill
model: resnet18
data_dir: /tmp/imagenet 

epochs: 100
batch_size: 64

sched: step
decay_epochs: 300
warmup_epochs: 5

# smoothing to zero
smoothing: 0

# Data and Model
hflip: 0.5
vflip: 0.0
crop_pct: 1.0

# Optimizer
lr: 10.0
opt: momsps
opt_kwargs: {'c': 0.4}
weight_decay: 0.00001
run_id: 0

# Other
workers: 16
log_wandb: true
wandb_project_name: iam-distill
