---

experiment: schedules
model: resnet50
data_dir: /tmp/imagenet 

epochs: 100
batch_size: 64

sched: wsd
warmup_epochs: 5
cooldown_epochs: 20
#sched_on_updates: true

# Data and Model
hflip: 0.5
vflip: 0.0
crop_pct: 1.0

# Optimizer
lr: 0.1
opt: momentumw
momentum: 0.9
weight_decay: 0.0001
run_id: 0

# Other
workers: 16
log_wandb: true
wandb_project_name: lr-schedules-imagenet
